export const RETAILER_ALPHANUM_POINTS = 1;
export const TOTAL_ROUND_POINTS = 50;
export const TOTAL_MULTIPLE_OF_QUARTER_POINTS = 25;
export const ITEMS_EVERY_TWO_POINTS = 5;
export const ITEMS_DESCRIPTION_MULTIPLIER = 0.2;
export const PURCHASE_DATE_ODD_POINTS = 6;
export const PURCHASE_TIME_WINDOW_POINTS = 10;
